### ISSUE TITLE
Add `chazz run` command to run commonly used scripts for specific setup

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/chazz#11]
I'm imagining something like `pipenv run` or `yarn run` where the configuration file can define a bunch of scripts to be run on the machines. This specifically comes up for scripts for resetting the FPGA, updating cerberus configuration, and restarting workers. These all can be done by `ssh`ing into machine but would be nicer to do using scripts.

**Comment by sampsyo** [comment]
Good idea!
